FROM nikolaik/python-nodejs
WORKDIR /usr/src/app
COPY . .

RUN pip install requests;exit 0
RUN pip install pandas; exit 0
RUN pip install numpy; exit 0
RUN pip install -U scikit-learn;exit 0
RUN npm install express;exit 0
RUN npm install request;exit 0
RUN npm install body-parser;exit 0


CMD ["python","-m","flask","run","--host=0.0.0.0"]
# docker run -p 5000:5000 id_image