# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    # network_mode: host
    image: mysql
    container_name: "db"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - volume:/mysql

  adminer:
    
    container_name: "adminer"
    image: adminer
    restart: always
    ports:
      - 8080:8080
    volumes:
      - volume:/adminer

  # app:
  #   build:
  #     dockerfile: /Dockerfile
  #   depends_on:
  #     - db
  #   restart: on-failure
  #   volumes:
  #     - volume:/app
  # fakedetector:
  #   container_name: "fakedetector"
  #   image: bbooss97/fakedetector
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db
  #     - rabbitmq
  #   restart: on-failure
  #   volumes:
  #     - volume:/fakedetector

  fakedetector:
    container_name: "fakedetector"
    
    image: bbooss97/fakedetector
    ports:
      - 3000:3000
    depends_on:
      - db
      - rabbitmq
    restart: on-failure
    volumes:
      - volume:/fakedetector

  stockpredictor:
    
    image: bbooss97/stockpredictorimage
    container_name: "stockpredictor"
    restart: on-failure
    depends_on: 
      - db
    ports:
      - 5000:5000
    volumes:
      - volume:/stockpredictor

  rabbitmq:
    
    container_name: 'rabbitmq'
    image: rabbitmq:3-management-alpine
    #container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
      - volume:/rabbitmq
volumes:
  volume:
